source 'https://rubygems.org' do
  gem 'ffi', '~> 1.12', '>= 1.12.2'
  gem 'nokogiri', '~> 1.11'
  gem 'watir', '~> 6.16', '>= 6.16.5'
  gem 'watir-webdriver', '~> 0.9.9'
  gem 'selenium-webdriver', '~> 3.142', '>= 2.27'
  gem 'pry', '~> 0.12.2'
  gem 'kimurai', '~> 1.4'
end